Modified the look and feel of the Expanded URLBar
cliqz/browser-ios pull request #235
Opened 2017-04-19 10:15 UTC by mahmoud-cliqz

@naira-cliqz @timotei-cliqz

2017-04-24 13:01 UTC, naira-cliqz requested changes
@mahmoud-cliqz

2017-04-24 13:01 UTC, naira-cliqz commented on Client/Frontend/Browser/TabLocationView.swift
> +        var urlText = ""
It would be better to have urlText retrieving logic separated in another function and the styling to have in current function.

2017-04-24 13:01 UTC, naira-cliqz commented on Client/Frontend/Browser/TabLocationView.swift
> +        urlTextFieldWidth = attributedString.size().width + 25
what is 25?

2017-04-24 13:01 UTC, naira-cliqz commented on Client/Frontend/Browser/URLBarView.swift
> +    private func adjustStatusBar() {
It would be more specific to rename the method name to smth like applyThemeOnStatusBar, adjust is too generic name for this method

2017-04-24 13:42 UTC, mahmoud-cliqz commented on Client/Frontend/Browser/TabLocationView.swift
> +        urlTextFieldWidth = attributedString.size().width + 25
it is a margin as `attributedString.size().width` does not accurately calculate the width

2017-04-25 12:23 UTC, mahmoud-cliqz commented
@naira-cliqz could you have a look after I did the required changes

2017-04-26 08:40 UTC, merged